language: android
jdk: oraclejdk7

android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.3
  - extra-android-m2repository
  - android-23
branches:
  except:
  - gh-pages
notifications:
  email:
  - andrei.zaiats@gmail.com
script: ./gradlew build check jacocoTestReport --stacktrace
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ./gradlew bintrayUpload -PbintrayUser=$BINTRAY_USER -PbintrayKey=$BINTRAY_KEY
cache:
  directories:
  - "$HOME/.gradle"
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/