language: android
jdk: oraclejdk7

android:
  components:
  - tools
  - platform-tools
  - build-tools-23.0.3
  - extra-android-m2repository
  - android-23
branches:
  except:
  - gh-pages
notifications:
  email:
  - andrei.zaiats@gmail.com
script: ./gradlew build --stacktrace
cache:
  directories:
  - "$HOME/.gradle"
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/